version: '3.7'

services:
    # MQTT Broker
    mosquitto:
        image: eclipse-mosquitto
        restart: always
        volumes:
            - ./mosquitto:/mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"

    # Datenbank
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: mysql
            MYSQL_USER: mqtt
            MYSQL_PASSWORD: smart-security
        volumes:
            - dbdata:/var/lib/mysql
            # - ./mariadb/conf/config-file.cnf:/etc/mysql/conf.d/config-file.cnf:ro
        ports:
            - "3306:3306"
    
    # Datenbank Web-Administration
    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080

    # Receiver, schreibt MQTT-Nachrichten in die MariaDB
    mqtt2mysql:
        image: davidlor/python-autoclonable-app
        depends_on: 
            - db
        environment: 
            - GIT_REPOSITORY=https://github.com/David-Lor/MQTT2MySQL.git
            - GIT_BRANCH=master
            - APP_NAME=MQTT2MySQL
            - MQTT_BROKER=mosquitto
            - MQTT_PORT=1883
            - MQTT_KEEPAPIVE=60
            - MQTT_QOS=2
            - SQL_USER=mqtt
            - SQL_PASSWORD=smart-security
            - SQL_DATABASE=mqtt
            - SQL_HOST=db
            - SQL_PORT=3306
    
    # Dashboard für das Backend, visualisiert Daten aus der MariaDB
    grafana:
        image: grafana/grafana
        restart: always
        depends_on: 
            - db
        ports: 
            - 3000:3000
        volumes:
            - ./grafana/provisioning:/etc/grafana/provisioning
            # - ./grafana/dashboards:/etc/grafana/dashboards
        environment:
            - SQL_HOST=db
            - SQL_PORT=3306
            - SQL_DATABASE=mqtt
            - SQL_USER=mqtt
            - SQL_PASSWORD=smart-security


volumes:
    # Docker-Volume für die MariaDB (persistenter Datenspeicher)
    dbdata: