version: '3.7'

services:
    # MQTT Broker
    mosquitto:
        image: eclipse-mosquitto
        # build: mosquitto/
        restart: always
        volumes:
            - "./mosquitto/config:/mosquitto/config"
            - mosquitto_data:/mosquitto/data
            - mosquitto_log:/mosquitto/log
        ports:
            - "1883:1883"
            - "9001:9001"

volumes:
    mosquitto_data:
    mosquitto_log:
