FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:latest-run

# Workaround, damit RPi.GPIO während der Installation kompiliert werden kann
#RUN apt-get -y update; apt-get -y upgrade; apt-get -y install build-essential

WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.conf .
COPY ./src .

CMD ["python", "app.py"]