FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:latest-run

WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.conf .
COPY ./src .

CMD ["python", "app.py"]